config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#index"

  resources :events
  resources :products, only: [:edit, :update, :destroy]

  resources :users, only: [:show] do
    resources :products, only: [:new, :create]
    resources :orders
  end

  resources :orders do
    get :send_order_mail, to: 'orders#send_order_mail', as: :send_order_mail
    resources :product_orders, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :user_events, only: [:create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :events, only: [:index, :show]
      resources :user_events, only: [:index]
    end
  end
end

app/models/product_order.rb
class ProductOrder < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true
  validates :quantity, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, format: {with: /\A\d{0,2}\.?\d{0,1}\z/}
  validates :product_id, presence: true
  validates :order_id, presence: true
end

app/controllers/product_orders_controller.rb
class ProductOrdersController < ApplicationController
  def new
    @product_order = ProductOrder.new
    @order = Order.find(params[:order_id])
    @user = @order.user
    @products = Product.where(grower_id: @user.id)
    @purchased = ProductOrder.where(order: @order)
  end

  def create
    @product_order = ProductOrder.new(product_order_params)

    @order = Order.find(params[:order_id])
    @user = @order.user
    @products = Product.where(grower_id: @user.id)
    @purchased = ProductOrder.where(order: @order)

    if @product_order.save
      flash[:notice] = "Successfully added to cart!"
      redirect_to new_order_product_order_path(@order)
    else
      flash[:notice] = "Please review the error messages."
      render :new
    end
  end

  def edit
    @product_order = ProductOrder.find(params[:id])
    @order = Order.find(params[:order_id])
    @user = @order.user
    @products = Product.where(grower_id: @user.id)
    @purchased = ProductOrder.where(order: @order)
  end

  def update
    @product_order = ProductOrder.find(params[:id])
    @order = Order.find(params[:order_id])
    @user = @order.user
    @products = Product.where(grower_id: @user.id)
    @purchased = ProductOrder.where(order: @order)
    if @product_order.update_attributes(product_order_params)
      flash[:notice] = 'Order was successfully updated.'
      redirect_to new_order_product_order_path(@order)
    else
      flash[:alert] = 'Please check the errors for your order.'
      render action: 'edit'
    end
  end

  def destroy
    @product_order = ProductOrder.find(params[:id])
    @order = Order.find(params[:order_id])
    @user = @order.user
    @products = Product.where(grower_id: @user.id)
    @purchased = ProductOrder.where(order: @order)

    if @product_order.destroy!
      flash[:notice] = "Item deleted from order."
      render :new
    end
  end

  private

  def product_order_params
    params.require(:product_order).permit(:product_id, :quantity).merge(order: Order.find(params[:order_id]))
  end



end

app/views/product_orders/_form.html.erb
<%= form_for [@order, @product_order] do |f| %>
  <% if @product_order.errors.any? %>
      <div id="error_explanation-orders">
        <h2><%= pluralize(@product_order.errors.count, "error") %> prohibited this item from being saved:</h2>

        <% @product_order.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </div>
  <% end %>

  <table class="order-table">
    <tr class="order-table">
      <td class="order-table">
        <%= f.label :product_id %> <br>
        <%= f.collection_select :product_id, @products, :id, :name %>
      </td>
      <td class="order-table">
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
      </td>
    </tr>
  </table>

  <div class="event-form">
    <%= f.submit 'Add to Cart', class: "event-form-submit" %>
  </div>
<% end %>

app/views/product_orders/edit.html.erb
<%= render 'form' %>

app/views/product_orders/new.html.erb
<div class="form-div">
  <h2>Order Continued</h2>
<table>
  <tr>
    <td>
      Name:
    </td>
    <td>
      <%= @order.name %>
    </td>
  </tr>
  <tr>
    <td>Email:</td>
    <td><%= @order.email %></td>
  </tr>
  <tr>
    <td>Event:</td>
    <td><%= @order.event.name %></td>
  </tr>
</table>
  <%= button_to "Edit Order Info", edit_order_path(@order), method: :get, class: "cancel" %>
  <h4>Currently in your cart:</h4>
    <% if @purchased %>
      <table class="order">
        <tr>
          <th class="order">
            Product
          </th>
          <th class="order">
            Price/Unit
          </th>
          <th class="order">
            Amount Purchased
          </th>
        </tr>
        <% @purchased.each do |item| %>
          <tr class="order">
            <td>
              <%= item.product.name %>
            </td>
            <td>
              <%= item.product.price %> / <%= item.product.unit %>
            </td>
            <td>
              <%= item.quantity %>
            </td>
            <td>
              <%= button_to "Edit", edit_order_product_order_path(@order, item), method: :get, class: "button-order" %>
            </td>
            <td>
              <%= button_to "Delete", { controller: :product_orders, action: 'destroy', id: item.id }, method: :delete, class: "button-order delete"  %>
            </td>
          </tr>
        <% end %>
      </table>
    <% end %>

  <hr>
<h4>Add More!</h4>
<%= render 'form' %>
<%= button_to "I'm done", { controller: :orders, action: "send_order_mail" }, method: :get, class: "event-form-submit done" %>
<%= button_to "Cancel", { controller: :orders, action: 'destroy', id: @order.id }, method: :delete, class: "cancel"  %>
</div>