config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#index"

  resources :events
  resources :products, only: [:edit, :update, :destroy]

  resources :users, only: [:show] do
    resources :products, only: [:new, :create]
    resources :orders
  end

  resources :orders do
    get :send_order_mail, to: 'orders#send_order_mail', as: :send_order_mail
    resources :product_orders, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :user_events, only: [:create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :events, only: [:index, :show]
      resources :user_events, only: [:index]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, foreign_key: "grower_id", dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :user_events, foreign_key: "grower_id", dependent: :destroy
  mount_uploader :avatar, AvatarUploader

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :company, presence: true
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :zip, length: { minimum: 5, maximum: 10 }
  validates :zip, format: { with: /\b\d{5}(-\d{4})?\b/ }
  validates :email, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i }



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    
    @user_events = UserEvent.where(grower_id: params[:id])
    @events = []
    @user_events.each do |event|
      @events << event.event
    end
    
    @user_created = Event.where(user_id: params[:id])
    @user_created.each do |event|
      @events << event
    end
    
    @products = Product.where(grower_id: params[:id])
  end
end

app/views/users/show.html.erb
<h2 class="profile-header company"><%= @user.company %></h2>

<h3 class="profile-header">Products</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Price (USD)</th>
    <th>Unit</th>
    <% if (user_signed_in?) && (@user.id == current_user.id) %>
      <th>Edit/Delete</th>
    <% end %>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.unit %></td>
      <% if (user_signed_in?) && (@user.id == current_user.id) %>
        <td><%= button_to "Edit", edit_product_path(product), method: :get, id: "edit-button" %> <%= button_to "Delete", product_path(product), method: :delete, id: "delete-button" %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<h3 class="profile-header">Events</h3>
  <table>
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Location</th>
    </tr>
    <% @events.each do |event| %>
      <tr>
        <td><%= link_to event.name, event_path(event), class: "event-list" %></td>
        <td><%= event.start_time.strftime("%D — %l:%M %p") %></td>
        <td><%= event.city %>, <%= event.state %></td>
      </tr>
    <% end %>
  </table>

<h4 class="welcome-events">Like what you see? <%=link_to "Make an order!", new_user_order_path(@user), class: "event-list"%></h4>

<h3 class="profile-header">About</h3>

<div id="user-about">
  <img src="<%= @user.avatar %>", id="avatar" />
  <h4>Owner</h4>
  <p><%= @user.first_name %> <%= @user.last_name %></p>

  <h4>Address</h4>
  <p><%= @user.address %>, <%= @user.city %>, <%= @user.state %>; <%= @user.zip %></p>

  <h4>Contact</h4>
  <p><%= @user.email %></p>

  <% if (user_signed_in?) && (@user.id == current_user.id) %>
  <h4>Page Admin</h4>
    <%= link_to "Add new product", new_user_product_path(@user), class: "event-list profile-links" %><br>
    <%= link_to "Edit Profile", edit_user_registration_path, class: "event-list profile-links"%>
  <% end %>
<div>