config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#index"

  resources :events
  resources :products, only: [:edit, :update, :destroy]

  resources :users, only: [:show] do
    resources :products, only: [:new, :create]
    resources :orders
  end

  resources :orders do
    get :send_order_mail, to: 'orders#send_order_mail', as: :send_order_mail
    resources :product_orders, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :user_events, only: [:create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :events, only: [:index, :show]
      resources :user_events, only: [:index]
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :user_events, dependent: :destroy
  has_many :orders

  STATES = [
    ["AK", "Alaska"],
    ["AL", "Alabama"],
    ["AR", "Arkansas"],
    ["AZ", "Arizona"],
    ["CA", "California"],
    ["CO", "Colorado"],
    ["CT", "Connecticut"],
    ["DE", "Delaware"],
    ["FL", "Florida"],
    ["GA", "Georgia"],
    ["HI", "Hawaii"],
    ["IA", "Iowa"],
    ["ID", "Idaho"],
    ["IL", "Illinois"],
    ["IN", "Indiana"],
    ["KS", "Kansas"],
    ["KY", "Kentucky"],
    ["LA", "Louisiana"],
    ["MA", "Massachusetts"],
    ["MD", "Maryland"],
    ["ME", "Maine"],
    ["MI", "Michigan"],
    ["MN", "Minnesota"],
    ["MO", "Missouri"],
    ["MS", "Mississippi"],
    ["MT", "Montana"],
    ["NC", "North Carolina"],
    ["ND", "North Dakota"],
    ["NE", "Nebraska"],
    ["NH", "New Hampshire"],
    ["NJ", "New Jersey"],
    ["NM", "New Mexico"],
    ["NV", "Nevada"],
    ["NY", "New York"],
    ["OH", "Ohio"],
    ["OK", "Oklahoma"],
    ["OR", "Oregon"],
    ["PA", "Pennsylvania"],
    ["RI", "Rhode Island"],
    ["SC", "South Carolina"],
    ["SD", "South Dakota"],
    ["TN", "Tennessee"],
    ["TX", "Texas"],
    ["UT", "Utah"],
    ["VA", "Virginia"],
    ["VI", "Virgin Islands"],
    ["VT", "Vermont"],
    ["WA", "Washington"],
    ["WI", "Wisconsin"],
    ["WV", "West Virginia"],
    ["WY", "Wyoming"]
  ]

  validates :name, presence: true
  validates :description, length: { maximum: 2000 }
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :event_url, format: { with: /https?:\/\/[\S]+/, allow_blank: true }
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :user_id, presence: true

  def self.search(search)
    where("name ILIKE ? OR city ILIKE ? OR state ILIKE ?", "%#{search}%",
      "%#{search}%", "%#{search}%")
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApplicationController

  def index
    @events = Event.order("updated_at DESC").all
    render json: @events
  end

  def show
    @event = Event.find(params[:id])
    render json: @event, serializer: EventSerializer
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all

    if !Event.search(params[:search]).empty?
      @events = Event.search(params[:search]).order("created_at DESC")
    else
      flash[:notice] = "Sorry that event doesn't exist. Peruse these instead!"
      @events = Event.all.order("created_at DESC")
    end
  end

  def show
    @event = Event.find(params[:id])
    @attendees = UserEvent.where(event_id: params[:id])
  end

  def new
    @event = Event.new
    @state_collection = Event::STATES
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Event created!"
      UserMailer.event_email(@event.user).deliver_now
      redirect_to event_path(@event.id)
    else
      flash[:alert] = "Event not created; please review form."
      @state_collection = Event::STATES
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
    @state_collection = Event::STATES
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:notice] = 'Event was successfully updated.'
      redirect_to event_path(@event)
    else
      render action: 'edit'
      @state_collection = Event::STATES
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy!
      redirect_to root_path
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :start_time, :end_time, :address, :city, :state, :event_url).merge(user_id: current_user.id)
  end
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>

<% if @event.errors.any? %>
    <div id="error_explanation-events">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <% @event.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>

    </div>
<% end %>



    <div class="event-form">
      <%= f.label :name, 'Event Name' %> <br>
      <%= f.text_field :name %>
    </div>

    <div class="event-form">
      <%= f.label :description %> <br>
      <%= f.text_area :description %>
    </div>

    <div class="event-form">
      <%= f.label :start_time, 'Start' %> <br>
      <%= f.datetime_select :start_time, ampm: true%>


  </div>

  <div class="event-form">
    <%= f.label :end_time, 'End' %> <br>
    <%= f.datetime_select :end_time, ampm: true%>
  </div>

  <div class="event-form">
    <%= f.label :address %> <br>
    <%= f.text_field :address %>
  </div>

  <div class="event-form">
    <%= f.label :city %> <br>
    <%= f.text_field :city %>
  </div>

  <div class='row'>
    <%= f.label :state %> <br>
    <%= f.select :state, @state_collection %>
  </div>

  <div class="event-form">
    <%= f.label :event_url, 'Event URL' %> <br>
    <%= f.text_field :event_url %>
  </div>

  <div class="event-form">
    <%= f.submit 'Add Event', class: "event-form-submit" %>
  </div>

<% end %>

</div>

app/views/events/edit.html.erb
<div class="form-div">
<h2>Edit Event</h2>

<% if current_user && current_user == @event.user %>
  <%= render 'form' %>
<% else %>
  <p>You cannot edit an event you didn't create!</p>
<% end %>
</div>

app/views/events/index.html.erb
<h2>Search Results</h2>

<ul class="event-list">
  <% @events.each do |event| %>
  <div id="event-div-home">
    <li class="event-list"><%= link_to "#{event.name} – #{event.city}, #{event.state}", event_path(event.id), class: "event-list" %></li>
  </div>
  <% end %>
</ul>

app/views/events/new.html.erb
<div class="form-div">
<h2>Add New Event</h2>

  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div id="event-div">
  <h2 id="event-title"><%= @event.name %></h2>
  <div id="app"></div>

  <% if (user_signed_in? && !UserEvent.find_by(grower: current_user, event: @event))%>
    <div id="event-button">
      <%= button_to "Attending", { controller: "user_events", action: "create", event_id: @event, grower_id: current_user } , method: :post, id: "attending-button" %>
    </div>
  <% elsif UserEvent.find_by(grower: current_user, event: @event) %>
    <div id="event-button">
      <%= button_to "Not Attending", { controller: "user_events", action: "destroy", event_id: @event, grower_id: current_user } , method: :delete, id: "not-attending-button" %>
    </div>
  <% end %>

  <% if current_user && current_user == @event.user %>
    <%= button_to "Edit", edit_event_path(@event), method: :get, id: "edit-button" %>
    <%= button_to "Delete",  event_path(@event), method: :delete, id: "delete-button"%>
  <% end %>

</div>