config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#index"

  resources :events
  resources :products, only: [:edit, :update, :destroy]

  resources :users, only: [:show] do
    resources :products, only: [:new, :create]
    resources :orders
  end

  resources :orders do
    get :send_order_mail, to: 'orders#send_order_mail', as: :send_order_mail
    resources :product_orders, only: [:new, :create, :edit, :update, :destroy]
  end

  resources :user_events, only: [:create, :destroy]

  namespace :api do
    namespace :v1 do
      resources :events, only: [:index, :show]
      resources :user_events, only: [:index]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrbGarden</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <nav>
      <ul id="sign-in-list">
        <li id="title"><%= link_to "UrbGarden", root_path, id: "home" %></li>
        <li id="search">
          <%= form_tag(events_path, method: "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Events" %>
            <%= submit_tag "Search", name: nil, id: "search-submit" %>
          <% end %>
        </li>
        <% if user_signed_in? %>
          <li id="signed-in">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "sign-in-link" %>
            <%= link_to 'Profile', user_path(current_user), class: "sign-in-link" %>
          </li>
        <% else %>
          <li id="sign-up">
            <%= link_to 'Sign Up', new_user_registration_path, class: "sign-in-link" %>
          </li>
          <li id="sign-in">
            <%= link_to 'Sign In', new_user_session_path, class: "sign-in-link" %>
          </li>
        <% end %>
      </ul>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>